### PR TITLE
Port to Collabwrapper

### LINKED ISSUE #5: Fix Collaboration.
Collaboration is currently broken and needs to be fixed, collabwrapper can be used in place of `ChatTube`.

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
Got merge conflicts in my branch. However 7b9cf42 can be cherry-picked. @quozl @chimosky Please review. Fixes #5

### CODE REVIEW

**Comment by quozl** [comment]
Merge conflicts are because your branch deviates from _master_ as at fa0bc74e8bd018df3a7b6d5e3ba10c72adb95660.  Use a git history visualisation; it is something that GitHub just doesn't do.  (Because the GitHub workflow is a fine tuned subset of the much wider git workflow; i.e. it is dumbed down.)

Fix is to;
```
# fetch current master
git fetch
# repoint your collab branch to current master
git reset --hard 55c1cce07e9e62967d1ab00636500083f8c77308
# reapply your commits but not the first one, since it is on master already
git cherry-pick 02dc3 cc374 e9d22 e9f38 9418 d7e2 7b9c
# verify nothing is different
git diff 7b9c
# push here
git push --force
```

**Comment by Saumya-Mishra9129** [comment]
> Merge conflicts are because your branch deviates from master as at fa0bc74. Use a git history visualisation; it is something that GitHub just doesn't do. (Because the GitHub workflow is a fine tuned subset of the much wider git workflow; i.e. it is dumbed down.)

Thanks @quozl , It helped finally..No conflicts now. :smile:

**Comment by quozl** [comment]
You appear to have cherry-picked only one of your original seven commits.

**Comment by Saumya-Mishra9129** [comment]
> You appear to have cherry-picked only one of your original seven commits.

Yeah!! It worked this way :sweat_smile:

**Comment by quozl** [comment]
I tried it, but did not know how to test.

**Comment by chimosky** [comment]
Tested and made an additional commit, the activity state is shared.

**Pull request merged**
